version: "3"

services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_DB: postgres
    volumes:
      - postgres:/data/postgres

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_DB: postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres: