"""Add cards

Revision ID: d673da771d87
Revises: 
Create Date: 2022-09-05 15:44:53.793444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd673da771d87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Numeric(scale=19), nullable=False),
    sa.Column('range_start', sa.Numeric(scale=19), nullable=False),
    sa.Column('range_end', sa.Numeric(scale=19), nullable=False),
    sa.Column('issuer_country', sa.String(), nullable=True),
    sa.Column('issuer_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_range_end'), 'cards', ['range_end'], unique=True)
    op.create_index(op.f('ix_cards_range_start'), 'cards', ['range_start'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_range_start'), table_name='cards')
    op.drop_index(op.f('ix_cards_range_end'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
